// +build !ignore_autogenerated

// Copyright The OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkOtelClusterReceiver) DeepCopyInto(out *SplunkOtelClusterReceiver) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkOtelClusterReceiver.
func (in *SplunkOtelClusterReceiver) DeepCopy() *SplunkOtelClusterReceiver {
	if in == nil {
		return nil
	}
	out := new(SplunkOtelClusterReceiver)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplunkOtelClusterReceiver) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkOtelClusterReceiverList) DeepCopyInto(out *SplunkOtelClusterReceiverList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SplunkOtelClusterReceiver, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkOtelClusterReceiverList.
func (in *SplunkOtelClusterReceiverList) DeepCopy() *SplunkOtelClusterReceiverList {
	if in == nil {
		return nil
	}
	out := new(SplunkOtelClusterReceiverList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SplunkOtelClusterReceiverList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkOtelClusterReceiverSpec) DeepCopyInto(out *SplunkOtelClusterReceiverSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkOtelClusterReceiverSpec.
func (in *SplunkOtelClusterReceiverSpec) DeepCopy() *SplunkOtelClusterReceiverSpec {
	if in == nil {
		return nil
	}
	out := new(SplunkOtelClusterReceiverSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SplunkOtelClusterReceiverStatus) DeepCopyInto(out *SplunkOtelClusterReceiverStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SplunkOtelClusterReceiverStatus.
func (in *SplunkOtelClusterReceiverStatus) DeepCopy() *SplunkOtelClusterReceiverStatus {
	if in == nil {
		return nil
	}
	out := new(SplunkOtelClusterReceiverStatus)
	in.DeepCopyInto(out)
	return out
}
